### PR TITLE
Feature/28 emigration component

### LINKED ISSUE #28: Build an Emigration module
- [x] Start from the Mortality component and write a new Emigration component that implements emigration based on rates from (#27 ).
- [x] Have a test_Emigration.py
- [x] Add implementation into test_pipeline.py
- [x] Run in notebook pipeline with Fertility and Mortality

### PR DESCRIPTION
**Pull request by crangelsmith**
Closes #28 

- [x] Start from the Mortality component and write a new Emigration component that implements emigration based on rates from (#27 ).
- [x] Have a test_Emigration.py
- [x] Add implementation into test_pipeline.py
- [x] Merge Immigration implementation into this PR

### CODE REVIEW

**Comment by crangelsmith** [comment]
Hi @kasra-hosseini, I have some issues running the notebooks, so I'll submit this PR and work on the notebooks on the next one related to #36

**Comment by kasra-hosseini** [comment]
@crangelsmith Thanks for the changes. All look great! As already mentioned in https://github.com/alan-turing-institute/vivarium_public_health_spenser/issues/36, I changed the immigration component to be compatible with fertility (and the other two components). There are some other minor changes. Would you please take a look at them?

**Comment by kasra-hosseini** [comment]
The notebook (pipeline 5) is empty now, but it has been tested. I am running it now over the whole dataset using all components. I will share the results here.

**Comment by kasra-hosseini** [comment]
@crangelsmith `notebooks/pipeline_005_fertility_mortality_emigration_immigration.ipynb` is not empty anymore :)

**Pull request merged**
